apiVersion: v1
kind: Service
metadata:
  name: plumber-db
  labels:
    app: plumber-db
spec:
  type: ClusterIP
  selector:
    app: plumber-db
  ports:
  - port: 3306
    targetPort: 3306

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plumber-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plumber-db
  template:
    metadata:
      labels:
        app: plumber-db
    spec:
      containers:
        - name: plumber-db
          image: mysql:5.6
          ports:
            - containerPort: 3306
          env:
          - name: MYSQL_RANDOM_ROOT_PASSWORD
            value: "yes"
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: plumber-secret
                key: DB_DATABASE
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: plumber-secret
                key: DB_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: plumber-secret
                key: DB_PASS
          volumeMounts:
            - name: plumber-db-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: plumber-db-persistent-storage
          persistentVolumeClaim:
            claimName: plumber-db-pv-claim
