apiVersion: v1
kind: Service
metadata:
  name: plumber-storage
  labels:
    app: plumber-storage
spec:
  type: LoadBalancer
  selector:
    app: plumber-storage
  ports:
  - port: 9000
    targetPort: 9000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plumber-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plumber-storage
  template:
    metadata:
      labels:
        app: plumber-storage
    spec:
      containers:
        - name: plumber-storage
          image: minio/minio
          ports:
            - containerPort: 9000
          command: ["minio"]
          args: ["server", "/data"]
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: plumber-secret
                  key: AWS_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: plumber-secret
                  key: AWS_SECRET_KEY
          volumeMounts:
            - name: plumber-storage-persistent-storage
              mountPath: /data
      volumes:
        - name: plumber-storage-persistent-storage
          persistentVolumeClaim:
            claimName: plumber-storage-pv-claim
