apiVersion: v1
kind: Service
metadata:
  name: plumber-db
  labels:
    app: plumber-db
spec:
  selector:
    app: plumber-db
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: plumber-storage
  labels:
    app: plumber-storage
spec:
  selector:
    app: plumber-storage
  ports:
  - port: 9000
    targetPort: 9000
  type: LoadBalancer

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plumber-db-pv-claim
  labels:
    app: pluber-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plumber-storage-pv-claim
  labels:
    app: pluber-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plumber-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plumber-db
  template:
    metadata:
      labels:
        app: plumber-db
    spec:
      containers:
        - name: plumber-db
          image: mysql:5.6
          ports:
            - containerPort: 3306
          env:
          - name: MYSQL_RANDOM_ROOT_PASSWORD
            value: "yes"
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: plumber-secret
                key: DB_DATABASE
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: plumber-secret
                key: DB_USER
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: plumber-secret
                key: DB_PASS
          volumeMounts:
            - name: plumber-db-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: plumber-db-persistent-storage
          persistentVolumeClaim:
            claimName: plumber-db-pv-claim

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plumber-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plumber-storage
  template:
    metadata:
      labels:
        app: plumber-storage
    spec:
      containers:
        - name: plumber-storage
          image: minio/minio
          ports:
            - containerPort: 9000
          command: ["minio"]
          args: ["server", "/data"]
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: plumber-secret
                  key: AWS_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: plumber-secret
                  key: AWS_SECRET_KEY
          volumeMounts:
            - name: plumber-storage-persistent-storage
              mountPath: /data
      volumes:
        - name: plumber-storage-persistent-storage
          persistentVolumeClaim:
            claimName: plumber-storage-pv-claim

