apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plumber-db-pv-claim
  labels:
    app: pluber-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plumber-storage-pv-claim
  labels:
    app: pluber-storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
