#
# This code was generated by code generator
#
import json


class api_login_req:
    
    user_id: str
    
    @classmethod
    def deserialize(cls, data_str: str):
        result = api_login_res
        data = json.loads(data_str)
        
        result.user_id = data["user_id"]
        
        return result


class api_login_res:
    
    user_id: str
    
    def serialize(self):
        data = {}
        
        data["user_id"] = self.user_id
        
        return json.dumps(data, ensure_ascii=False)


class api_finish_game_req:
    
    user_id: str
    
    score: int
    
    @classmethod
    def deserialize(cls, data_str: str):
        result = api_finish_game_res
        data = json.loads(data_str)
        
        result.user_id = data["user_id"]
        
        result.score = data["score"]
        
        return result


class api_finish_game_res:
    
    def serialize(self):
        data = {}
        
        return json.dumps(data, ensure_ascii=False)

