/* 
 * This code was generated by code generator 
 */
using UnityEngine;
using System;

namespace Protocol
{
    
    [Serializable]
    public class api_login_req
    {
        
        public string user_id;
        
        public string Serialize()
        {
            return JsonUtility.ToJson(this);
        }

        public static string GetEndpoint()
        {
            return "/api_login";
        }
    }

    [Serializable]
    public class api_login_res
    {
        
        public string user_id;
        
        public static api_login_res Deserialize(string jsonString)
        {
            return JsonUtility.FromJson<api_login_res>(jsonString);
        }
    }
    
    [Serializable]
    public class api_finish_game_req
    {
        
        public string user_id;
        
        public int score;
        
        public string Serialize()
        {
            return JsonUtility.ToJson(this);
        }

        public static string GetEndpoint()
        {
            return "/api_finish_game";
        }
    }

    [Serializable]
    public class api_finish_game_res
    {
        
        public static api_finish_game_res Deserialize(string jsonString)
        {
            return JsonUtility.FromJson<api_finish_game_res>(jsonString);
        }
    }
    
}